package javasign.com.dompetsehat.injection.component;

import android.content.Context;
import dagger.Component;
import javasign.com.dompetsehat.data.HeaderInterceptor;
import javasign.com.dompetsehat.injection.ActivityContext;
import javasign.com.dompetsehat.injection.PerActivity;
import javasign.com.dompetsehat.injection.module.ActivityModule;
import javasign.com.dompetsehat.ui.activities.ask.AskActivity;
import javasign.com.dompetsehat.ui.activities.RuntimePermissionsActivity;
import javasign.com.dompetsehat.ui.activities.account.AddAccountActivity;
import javasign.com.dompetsehat.ui.activities.account.AddAccountBankActivity;
import javasign.com.dompetsehat.ui.activities.account.AddAccountDompetActivity;
import javasign.com.dompetsehat.ui.activities.account.FinalCreateAccountActivity;
import javasign.com.dompetsehat.ui.activities.account.ManageEachAccountActivity;
import javasign.com.dompetsehat.ui.activities.account.NewManageAccountActivity;
import javasign.com.dompetsehat.ui.activities.badges.BadgesActivity;
import javasign.com.dompetsehat.ui.activities.budget.AddBudgetActivity;
import javasign.com.dompetsehat.ui.activities.budget.BudgetActivity;
import javasign.com.dompetsehat.ui.activities.budget.BudgetDetailActivity;
import javasign.com.dompetsehat.ui.activities.budget.BudgetResultEstimatorActivity;
import javasign.com.dompetsehat.ui.activities.budget.BudgetSetupActivity;
import javasign.com.dompetsehat.ui.activities.budget.SchedulerMainActivity;
import javasign.com.dompetsehat.ui.activities.category.AddCategory;
import javasign.com.dompetsehat.ui.activities.category.CategoryActivity;
import javasign.com.dompetsehat.ui.activities.category.listfragment.ListCategoryFragment;
import javasign.com.dompetsehat.ui.activities.closing.ClosingActivity;
import javasign.com.dompetsehat.ui.activities.comission.ComissionActivity;
import javasign.com.dompetsehat.ui.activities.debts.AddDebtActivity;
import javasign.com.dompetsehat.ui.activities.debts.DebtsActivity;
import javasign.com.dompetsehat.ui.activities.feedback.FeedbackActivity;
import javasign.com.dompetsehat.ui.activities.feedback.ThankFullActivity;
import javasign.com.dompetsehat.ui.activities.forgot.ForgotPasswordActivity;
import javasign.com.dompetsehat.ui.activities.help.HelpActivity;
import javasign.com.dompetsehat.ui.activities.home.HomeActivity;
import javasign.com.dompetsehat.ui.activities.institusi.FormEditFieldActivity;
import javasign.com.dompetsehat.ui.activities.institusi.InstitusiActivity;
import javasign.com.dompetsehat.ui.activities.institusi.ListAvailableInstitusiActivity;
import javasign.com.dompetsehat.ui.activities.institusi.ListInstitusiActivity;
import javasign.com.dompetsehat.ui.activities.institusi.dialog.VerificationDialog;
import javasign.com.dompetsehat.ui.activities.institusi.vendor.manulife.FinalRegistrationMamiAcitivity;
import javasign.com.dompetsehat.ui.activities.institusi.vendor.manulife.InputReferralCodeMamiActivity;
import javasign.com.dompetsehat.ui.activities.institusi.vendor.manulife.LoginKlikMamiActivity;
import javasign.com.dompetsehat.ui.activities.institusi.vendor.manulife.ManulifeHomePageActivity;
import javasign.com.dompetsehat.ui.activities.institusi.vendor.manulife.RegisterMamiActivity;
import javasign.com.dompetsehat.ui.activities.institusi.vendor.manulife.TermsAndConditionManulife;
import javasign.com.dompetsehat.ui.activities.landing.LandingPages;
import javasign.com.dompetsehat.ui.activities.login.SignInActivity;
import javasign.com.dompetsehat.ui.activities.main.NewMainActivity;
import javasign.com.dompetsehat.ui.activities.main.ParentMain;
import javasign.com.dompetsehat.ui.activities.notification.GlobalNotificationActivity;
import javasign.com.dompetsehat.ui.activities.onestep.OneStepCloserActivity;
import javasign.com.dompetsehat.ui.activities.plan.AddPlanActivity;
import javasign.com.dompetsehat.ui.activities.plan.CustomPlanActivity;
import javasign.com.dompetsehat.ui.activities.plan.DanaDaruratActivity;
import javasign.com.dompetsehat.ui.activities.plan.DanaKuliahActivity;
import javasign.com.dompetsehat.ui.activities.plan.DanaPensiunActivity;
import javasign.com.dompetsehat.ui.activities.plan.DetailPlanActivity;
import javasign.com.dompetsehat.ui.activities.plan.FinishingPlanActivity;
import javasign.com.dompetsehat.ui.activities.plan.FormEditFieldDanaKuliahActivity;
import javasign.com.dompetsehat.ui.activities.plan.ProductListInstitusiActivity;
import javasign.com.dompetsehat.ui.activities.plan.ProductListNonInstitusiActivity;
import javasign.com.dompetsehat.ui.activities.plan.SetupPlanActivity;
import javasign.com.dompetsehat.ui.activities.portofolio.DetailPortofolioActivity;
import javasign.com.dompetsehat.ui.activities.profile.EditProfileActivity;
import javasign.com.dompetsehat.ui.activities.profile.ProfileActivity;
import javasign.com.dompetsehat.ui.activities.referral.ReferralLoaderActivity;
import javasign.com.dompetsehat.ui.activities.reminder.AddReminderActivity;
import javasign.com.dompetsehat.ui.activities.reminder.ReminderActivity;
import javasign.com.dompetsehat.ui.activities.search.SearchActivity;
import javasign.com.dompetsehat.ui.activities.setting.SettingActivity;
import javasign.com.dompetsehat.ui.activities.setting.about.AboutActivity;
import javasign.com.dompetsehat.ui.activities.setting.export.ExportSettingActivity;
import javasign.com.dompetsehat.ui.activities.setting.sharing.InviteMemberSharingDataActivity;
import javasign.com.dompetsehat.ui.activities.setting.sharing.SharingDataActivity;
import javasign.com.dompetsehat.ui.activities.setting.sharing.SharingDataPermissionActivity;
import javasign.com.dompetsehat.ui.activities.setting.sharing.notif.NotificationActivity;
import javasign.com.dompetsehat.ui.activities.setting.sharing.permission.PermissionSettingActivity;
import javasign.com.dompetsehat.ui.activities.setting.switchmode.SwitchModeActivity;
import javasign.com.dompetsehat.ui.activities.setting.syncs.SyncSettingActivity;
import javasign.com.dompetsehat.ui.activities.tag.AddTagActivity;
import javasign.com.dompetsehat.ui.activities.tag.TagActivity;
import javasign.com.dompetsehat.ui.activities.transaction.AddTransactionActivity;
import javasign.com.dompetsehat.ui.activities.transaction.TransactionsActivity;
import javasign.com.dompetsehat.ui.activities.transaction.listfragment.ListTransactionFragment;
import javasign.com.dompetsehat.ui.activities.trend.TrendsActivity;
import javasign.com.dompetsehat.ui.activities.verification.EmailVerificationActivity;
import javasign.com.dompetsehat.ui.activities.webview.WebLoaderActivity;
import javasign.com.dompetsehat.ui.dialogs.DialogPickCategory;
import javasign.com.dompetsehat.ui.fragments.account.NewManageAccountFragment;
import javasign.com.dompetsehat.ui.fragments.budget.BudgetFragment;
import javasign.com.dompetsehat.ui.fragments.comission.ComissionFragment;
import javasign.com.dompetsehat.ui.fragments.debts.ListDebtFragment;
import javasign.com.dompetsehat.ui.fragments.feedback.FeedBackFragment;
import javasign.com.dompetsehat.ui.fragments.finplan.listfragment.PlanFragment;
import javasign.com.dompetsehat.ui.fragments.finplan.listfragment.PortofolioFragment;
import javasign.com.dompetsehat.ui.fragments.overview_v1.Old_OverViewFragment;
import javasign.com.dompetsehat.ui.fragments.overview_v1.listfragment.Old_OverviewCategoryExpenseFragment;
import javasign.com.dompetsehat.ui.fragments.overview_v1.listfragment.Old_OverviewCategoryIncomeFragment;
import javasign.com.dompetsehat.ui.fragments.overview_v1.listfragment.Old_OverviewFragmentNettIncome;
import javasign.com.dompetsehat.ui.fragments.overview_v1.listfragment.Old_OverviewTransactionExpenseFragment;
import javasign.com.dompetsehat.ui.fragments.overview_v1.listfragment.Old_OverviewTransactionIncomeFragment;
import javasign.com.dompetsehat.ui.fragments.overview_v2.OverviewFragment;
import javasign.com.dompetsehat.ui.fragments.overview_v2.listfragment.OvCategoryFragment;
import javasign.com.dompetsehat.ui.fragments.overview_v2.listfragment.OvNettIncomeFragment;
import javasign.com.dompetsehat.ui.fragments.overview_v2.listfragment.OvTransactionFragment;
import javasign.com.dompetsehat.ui.fragments.referral.ReferralFragment;
import javasign.com.dompetsehat.ui.fragments.timeline.NewTimelineFragment;

/**
 * Created by avesina on 2/12/16.
 */

@PerActivity @Component(dependencies = ApplicationComponent.class, modules = ActivityModule.class)
public interface ActivityComponent {

  @ActivityContext Context context();


  // Activity
  void inject(RuntimePermissionsActivity activity);
  void inject(SignInActivity activity);
  void inject(NewMainActivity activity);
  void inject(ParentMain activity);
  void inject(TransactionsActivity activity);
  void inject(CategoryActivity activity);
  void inject(LandingPages activity);
  void inject(OneStepCloserActivity activity);
  void inject(ProfileActivity activity);
  void inject(TrendsActivity activity);
  void inject(EditProfileActivity activity);
  void inject(AddBudgetActivity activity);
  void inject(BudgetActivity activity);
  void inject(AddTransactionActivity activity);
  void inject(AddReminderActivity activity);
  void inject(ReminderActivity activity);
  void inject(BudgetSetupActivity activity);
  void inject(DanaPensiunActivity activity);
  void inject(SetupPlanActivity activity);
  void inject(AddAccountActivity activity);
  void inject(AddAccountDompetActivity activity);
  void inject(FinishingPlanActivity activity);
  void inject(DanaDaruratActivity activity);
  void inject(CustomPlanActivity activity);
  void inject(BudgetResultEstimatorActivity activity);
  void inject(NewManageAccountActivity activity);
  void inject(AddPlanActivity activity);
  void inject(SearchActivity activity);
  void inject(FeedbackActivity activity);
  void inject(ManageEachAccountActivity activity);
  void inject(DanaKuliahActivity activity);
  void inject(SchedulerMainActivity activity);
  void inject(AddCategory activity);
  void inject(ComissionActivity activity);
  void inject(BadgesActivity activity);
  void inject(AddAccountBankActivity activity);
  void inject(ForgotPasswordActivity activity);
  void inject(DetailPlanActivity activity);
  void inject(FormEditFieldDanaKuliahActivity activity);
  void inject(HomeActivity activity);
  void inject(ProductListInstitusiActivity activity);
  void inject(ProductListNonInstitusiActivity activity);
  void inject(RegisterMamiActivity activity);
  void inject(ClosingActivity activity);
  void inject(SwitchModeActivity activity);
  void inject(SettingActivity activity);
  void inject(HelpActivity activity);
  void inject(ReferralLoaderActivity activity);
  void inject(FormEditFieldActivity activity);
  void inject(LoginKlikMamiActivity activity);
  void inject(FinalRegistrationMamiAcitivity activity);
  void inject(BudgetDetailActivity activity);
  void inject(InstitusiActivity activity);
  void inject(FinalCreateAccountActivity activity);
  void inject(AddTagActivity activity);
  void inject(DetailPortofolioActivity activity);
  void inject(ListInstitusiActivity activity);
  void inject(ThankFullActivity activity);
  void inject(InputReferralCodeMamiActivity activity);
  void inject(ExportSettingActivity activity);
  void inject(SyncSettingActivity activity);
  void inject(AboutActivity activity);
  void inject(SharingDataActivity activity);
  void inject(InviteMemberSharingDataActivity activity);
  void inject(NotificationActivity activity);
  void inject(SharingDataPermissionActivity activity);
  void inject(PermissionSettingActivity activity);
  void inject(WebLoaderActivity activity);
  void inject(ManulifeHomePageActivity activity);
  void inject(TermsAndConditionManulife activity);
  void inject(ListAvailableInstitusiActivity activity);
  void inject(AskActivity activity);
  void inject(TagActivity activity);
  void inject(DebtsActivity activity);
  void inject(AddDebtActivity activity);
  void inject(GlobalNotificationActivity activity);
  void inject(EmailVerificationActivity activity);

  // Fragment
  void inject(Old_OverViewFragment fragment);
  void inject(BudgetFragment fragment);
  void inject(ListCategoryFragment fragment);
  void inject(NewManageAccountFragment fragment);
  void inject(PlanFragment fragment);
  void inject(Old_OverviewFragmentNettIncome fragment);
  void inject(Old_OverviewCategoryIncomeFragment fragment);
  void inject(Old_OverviewCategoryExpenseFragment fragment);
  void inject(Old_OverviewTransactionExpenseFragment fragment);
  void inject(Old_OverviewTransactionIncomeFragment fragment);
  void inject(NewTimelineFragment fragment);
  void inject(ReferralFragment fragment);
  void inject(ComissionFragment fragment);
  void inject(PortofolioFragment fragment);
  void inject(ListTransactionFragment fragment);
  void inject(FeedBackFragment fragment);
  void inject(OverviewFragment fragment);
  void inject(OvNettIncomeFragment fragment);
  void inject(OvTransactionFragment fragment);
  void inject(OvCategoryFragment fragment);
  void inject(DialogPickCategory fragment);
  void inject(ListDebtFragment fragment);
  void inject(VerificationDialog dialog);

  void inject(HeaderInterceptor interceptor);

}
